#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: rob-robot-000
    realname: Robotnik Automation S.L.
    username: robot
    password: $6$Z2ZFK3VplTxBlX2w$blmQ9Um05Z0FG8AfqH1A/C3fPSVR7C.2X1ev9IcTj.SIICC0zwdRBY2nZTYp.DK/i9wuaXEq4wspJTNkgAeBP0
  refresh-installer:
  update: yes
  locale: en_US
  keyboard:
    layout: es
    # variant: es
  source:
    id: "ubuntu-server"
  ssh:
    install-server: yes
    authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtkQFf7sa+G1oAGkPC2fMR+qOqcE651SToEyVbR6aDFR9kYLSFLvzUA1W+hjDsI1uL5SuOQju1kDDDnNO0SjQOsffqw44L3D9CXqNPIAGs+6lBffDGd9A6e5yLpOuaXM5t9dMBq2SWV2Frq8gu0CR3NyHtFCzu87ghlKzaelaGWdIeyR+2HqtQr3t+ykCF5u0/+MLGWEHISpl+aV17+lvRB8qRNE0hZm7lSWTgJ2gRFVIGy69tsUCYf9+0KJDkM3sfvxzM2HyKNN60gkGDTH0BA4/ZTzqs8qbCylD1Jhgl+0ZNaIg6OkhyFBzESxrQpQkexOTtygtpv6YJM2liZTV7
    allow-pw: yes
  updates: all
  apt:
    mirror-selection:
      primary:
        - uri: http://archive.ubuntu.com/ubuntu
    sources:
      docker.list:
        source: >
          deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      ros.list:
        source: >
          deb [arch=amd64] http://packages.ros.org/ros/ubuntu focal main
        keyid: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: yes
          optional: yes
        eth1:
          dhcp4: yes
          optional: true
  storage:
    layout:
      name: lvm
      match:
        ssd: yes
      sizing-policy: all
  packages:
    - gnupg2
    - apt-transport-https
    - jq
    - powerline
    - fonts-powerline
    # - fzf
    - ack-grep
    - net-tools
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
    - ubuntu-desktop-minimal
    - screen
    - python3-rosdep
    - python3-rosinstall
    - python3-rosinstall-generator
    - build-essential
    - python3-wstool
    - ros-noetic-desktop-full
    - ros-noetic-transmission-interface
    - ros-noetic-effort-controllers
    - ros-noetic-joint-state-controller
    - ros-noetic-navigation
    - ros-noetic-ros-control
    - ros-noetic-ros-controllers
    - ros-noetic-velocity-controllers
    - ros-noetic-control-toolbox
    - ros-noetic-cmake-modules
    - ros-noetic-serial
    - ros-noetic-joystick-drivers
    - ros-noetic-rosbridge-server
    - ros-noetic-robot-localization
    - ros-noetic-twist-mux
    - ros-noetic-imu-tools
    - ros-noetic-mavros-*
    - ros-noetic-teb-local-planner
    - ros-noetic-ackermann*
    - ros-noetic-rosbridge-suite
    - ros-noetic-urg-node
    - ros-noetic-ar-track-alvar*
    - ros-noetic-move-base
    - ros-noetic-amcl
    - ros-noetic-libuvc-camera
    - ros-noetic-realsense2-camera
    - ros-noetic-rqt-joint-trajectory-controller
    - ros-noetic-psen-scan*
    - openssh-server
    - vim
    - subversion
    - git
    - apache2
    - mingetty
    - libpopt-dev
    - sysstat
    - ifstat
    - ntpdate
    - terminator
    - screen
    - libpcap-dev
    - socat
    - ffmpeg
    - python3-pip
    - python3-catkin-tools
    - python3-bloom
    - arp-scan
    - libmodbus*
    - net-tools
    - meld
    - libmysql++3v5
    - libmysql++-dev
  late-commands:
    - >
      wget
      https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      -O yq
    - chmod +x yq
    - mv yq /target/usr/local/bin/yq
  user-data:
    write_files:
      - path: /etc/modules-load.d/k8s.conf
        permissions: '0644'
        content: |
          overlay
          br_netfilter
    runcmd:
      - systemctl stop containerd
      - mkdir -p /etc/containerd
      - touch /etc/containerd/config.toml
      - containerd config default > /etc/containerd/config.toml
      - >
        sed -i
        's/SystemdCgroup = false/SystemdCgroup = true/'
        /etc/containerd/config.toml
      - systemctl start containerd
      - systemctl enable containerd
      - groupadd docker
      - usermod -aG docker robot
      - >
        sudo -u robot
        git clone --depth 1
        https://github.com/junegunn/fzf.git
        /home/robot/.fzf
      - sudo -u robot /home/robot/.fzf/install --all
      - >
        sudo -u robot
        echo
        "source export ROS_MASTER_URI='http://$HOSTNAME:11311'"
        >>/home/robot/.bashrc
      - >
        sudo -u robot
        echo
        "source /opt/ros/noetic/setup.bash"
        >>/home/robot/.bashrc
      - >
        sudo -u robot
        echo
        "source /usr/share/powerline/bindings/bash/powerline.sh"
        >>/home/robot/.bashrc
